#!/bin/bash
export LC_ALL=C

# Version and dependency check
mpv_version=$(mpv --version | head -1 | cut -d' ' -f2)
if [[ "$mpv_version" < "0.30" ]]; then
  error_exit "mpv_version $mpv_version is too old; requires 0.30+"
fi
command -v choose >/dev/null || error_exit "choose required"
command -v terminal-notifier >/dev/null || error_exit "terminal-notifier required"

error_exit() {
  local message="$1"
  echo "$message" >>/tmp/rofi-music.log
  notification "$message"
  exit 1
}

notification() {
  local message="$1"
  message="${message:0:50}"
  terminal-notifier -message "$message" >/dev/null 2>&1
}

playlists() {
  local playlists="$1"
  [ -d "$playlists" ] || error_exit "Playlists not found"
  (ls -1 "$playlists" | sort -f; echo "Exit")
}

songs() {
  local songs="$1"
  [ -d "$songs" ] || error_exit "Songs not found"
  echo "Play All"
  for file in "$songs"/*.{m4a,mp3,flac}; do
    [ -f "$file" ] && printf '%s\n' "${file##*/}";
  done | sort -f
}

main() {
  local playlists="${1:-$HOME/Music}"

  # Get number of playlists for dynamic rows
  local playlists_count=$(playlists "$playlists" | wc -l | awk '{print $1 + 1}')

  # Spawn initial menu with all detected playlists
  local menu=$(playlists "$playlists" | choose -w 24 -n "$playlists_count")
  [ -z "$menu" ] || [ "$menu" = "Exit" ] && { notification "Exiting"; exit 0; }

  # Saves selected playlist in buffer
  local selected_playlist="$playlists/$menu"

  # Get number of songs in playlist for dynamic rows
  local songs_count=$(songs "$selected_playlist" | wc -l | awk '{print $1 + 1}')

  # Spawn menu with all songs in selected playlist
  local choice=$(songs "$selected_playlist" | choose -w 36 -n "$songs_count")
  [ -z "$choice" ] && { notification "No song selected"; exit 1; }

  # Logic for playing all or song selection
  if [ "$choice" = "Play All" ]; then
    notification "Playing all songs in $menu"
    mpv --no-video --shuffle "$selected_playlist"/*.{m4a,mp3,flac} --loop-playlist >/dev/null 2>&1 &
  else
    local selected_song="$selected_playlist/$choice"
    notification "Playing $choice"
    mpv --no-video "$selected_song" --loop >/dev/null 2>&1 &
  fi
}

if pkill -f mpv; then
  notification "Stopping playback"
else
  main "$@"
fi
